# Generated by Django 2.2 on 2023-01-02 04:55

import cloud.shortuuid
import dashboard.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('c_credentials', models.TextField()),
                ('salt', models.CharField(max_length=512)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', dashboard.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceLogic',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('logo_image', models.ImageField(null=True, upload_to='marketplace_logic_logo_image')),
                ('function_zip_file', models.FileField(null=True, upload_to='marketplace_logic_function_zip')),
                ('function_name', models.CharField(max_length=255, null=True)),
                ('handler', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('price', models.BigIntegerField(default=0)),
                ('setup_count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('funnel', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceLogicSetup',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('marketplace_logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MarketplaceLogic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceLogicComment',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('marketplace_logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MarketplaceLogic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='comment_user_set',
            field=models.ManyToManyField(blank=True, related_name='comment_user_set', through='dashboard.MarketplaceLogicComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='setup_user_set',
            field=models.ManyToManyField(blank=True, related_name='setup_user_set', through='dashboard.MarketplaceLogicSetup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=255)),
                ('event', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(editable=False, max_length=255)),
                ('target', models.CharField(editable=False, max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Tracker')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.CharField(default='aws', max_length=255)),
                ('region', models.CharField(default='ap-northeast-2', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
