# Generated by Django 2.1.4 on 2018-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField()),
                ('email', models.CharField(max_length=200)),
                ('password_s_hash', models.CharField(max_length=200)),
                ('c_aws_access_key', models.CharField(max_length=200)),
                ('c_aws_secret_key', models.CharField(max_length=200)),
            ],
        ),
    ]
