# Generated by Django 2.1.4 on 2019-01-20 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('recipe_id', models.CharField(max_length=255)),
                ('recipe_type', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('json_string', models.TextField()),
            ],
        ),
    ]
