# Generated by Django 2.1.4 on 2019-04-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='need_deploy',
            field=models.BooleanField(default=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='app',
            name='vendor',
            field=models.CharField(default='aws', max_length=255),
        ),
    ]
