# Generated by Django 2.1.9 on 2019-06-25 08:26

import cloud.shortuuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_marketplacelogiccomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLogicSetup',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketplacelogic',
            name='setup_count',
        ),
        migrations.RemoveField(
            model_name='marketplacelogic',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='marketplacelogiccomment',
            name='like_count',
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='comment_user_set',
            field=models.ManyToManyField(blank=True, related_name='comment_user_set', through='dashboard.MarketplaceLogicComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacelogicsetup',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MarketplaceLogic'),
        ),
        migrations.AddField(
            model_name='marketplacelogicsetup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='setup_user_set',
            field=models.ManyToManyField(blank=True, related_name='setup_user_set', through='dashboard.MarketplaceLogicSetup', to=settings.AUTH_USER_MODEL),
        ),
    ]
