# Generated by Django 2.1.7 on 2019-02-13 07:44

import cloud.shortuuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_app_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default=cloud.shortuuid.ShortUUID.uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.CharField(default=cloud.shortuuid.ShortUUID.uuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
