# Generated by Django 2.1.7 on 2019-05-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190403_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='app',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
