# Generated by Django 2.1.9 on 2019-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190625_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelogic',
            name='setup_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
