# Generated by Django 2.1.4 on 2018-12-15 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181215_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c_aws_access_key',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_aws_secret_key',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=512),
        ),
    ]
