# Generated by Django 2.1.4 on 2019-05-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190501_1224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set(),
        ),
    ]
