# Generated by Django 2.1.9 on 2019-06-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_marketplacelogic_setup_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplacelogiccomment',
            old_name='parent',
            new_name='marketplace_logic',
        ),
        migrations.RenameField(
            model_name='marketplacelogicsetup',
            old_name='parent',
            new_name='marketplace_logic',
        ),
    ]
