# Generated by Django 2.1.4 on 2019-01-13 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20181216_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('json_string', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.App')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='c_aws_access_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_aws_secret_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=255),
        ),
    ]
