# Generated by Django 2.1.8 on 2019-05-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_log_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='content',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='log',
            name='error',
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(default='content', max_length=255),
            preserve_default=False,
        ),
    ]
