# Generated by Django 2.1.4 on 2019-01-13 12:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190113_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
