# Generated by Django 2.1.8 on 2019-06-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190609_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tracker_id',
            new_name='tracker',
        ),
    ]
