# Generated by Django 2.1.9 on 2019-06-19 14:14

import cloud.shortuuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190609_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLogic',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('logo_image', models.ImageField(upload_to='')),
                ('function_zip_file', models.FileField(null=True, upload_to='')),
                ('test_payloads', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceLogicImage',
            fields=[
                ('id', models.CharField(default=cloud.shortuuid.uuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('marketplace_logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.MarketplaceLogic')),
            ],
        ),
    ]
