# Generated by Django 2.1.9 on 2019-06-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_marketplacelogic_marketplacelogicimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacelogicimage',
            name='description',
        ),
    ]
