# Generated by Django 2.1.9 on 2019-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_marketplacelogicimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelogic',
            name='setup_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
