# Generated by Django 2.1.9 on 2019-06-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190620_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacelogicimage',
            name='marketplace_logic',
        ),
        migrations.RemoveField(
            model_name='marketplacelogic',
            name='test_payloads',
        ),
        migrations.DeleteModel(
            name='MarketplaceLogicImage',
        ),
    ]
