# Generated by Django 2.1.9 on 2019-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190620_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelogic',
            name='category',
            field=models.CharField(default='defaultstring', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='handler',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketplacelogic',
            name='runtime',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
