# Generated by Django 2.1.9 on 2019-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_marketplacelogic_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelogic',
            name='function_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
